### ISSUE TITLE
[Suggestion] Pin on Top

### ISSUE THREAD

**Issue by Suleman-Elahi** [oormicreations/ClipboardPlus#1]
Add an option in the tool to pin it above all windows. Currently it disappears after switching to another window. Pin on top will help users to copy content successively without bringing back the interface of this tool again n again.

Thanks...

**Comment by oormicreations** [comment]
Sure. Added to TODO.
Thanks for the suggestion.

**Comment by Suleman-Elahi** [comment]
There is also another suggestion. Make current clipboard entries on the software persistent like storing them to a temporary file. So, if a computer shut downs abnormally, user's clip won't be lost... !!!

Thanks !!!

**Comment by oormicreations** [comment]
Sure. Can be done. Thanks again for nice suggestions.
______________________________________
